[package]
name = "plgr-distr"
version = "0.1.0"
edition = "2021"

[dependencies]
ruc = "0.6"
secp256k1 = "0.20"
futures = "0.3.19"
serde_json = "1.0"
web3 = { git = "https://gitee.com/kt10/rust-web3", branch = "master" }
